[package]
name = "actix-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
utoipa = "5.2"
utoipa-swagger-ui = { version = "8", features = ["actix-web"] }
tokio = { version = "1", features = ["full"] }